// <auto-generated />
using System;
using Example.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example.DataAccessLayer.Migrations.SqlLite
{
    [DbContext(typeof(SqlLiteContext))]
    [Migration("20220712052253_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Example.Entites.concrete.Invoice", b =>
                {
                    b.Property<int>("LogicalRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("LogicalRef");

                    b.ToTable("INVOICE");
                });

            modelBuilder.Entity("Example.Entites.concrete.InvoiceLine", b =>
                {
                    b.Property<int>("LogicalRef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("InvoiceRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StFicheRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockRef")
                        .HasColumnType("INTEGER");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.HasKey("LogicalRef");

                    b.ToTable("StLine");
                });
#pragma warning restore 612, 618
        }
    }
}
